#ifndef _oem_OEM_CONSTRUCTION_H
#define _oem_OEM_CONSTRUCTION_H

#include <Rcpp.h>
#include <RcppEigen.h>

using namespace Rcpp;
using namespace RcppEigen;

RcppExport SEXP oem_fit_big(SEXP, 
                            SEXP, 
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP, 
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP,
                            SEXP, 
                            SEXP,
                            SEXP,
                            SEXP);

RcppExport SEXP oem_fit_dense(SEXP, 
                              SEXP, 
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP, 
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP,
                              SEXP, 
                              SEXP,
                              SEXP,
                              SEXP);

RcppExport SEXP oem_fit_logistic_dense(SEXP, 
                                       SEXP, 
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP, 
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP,
                                       SEXP, 
                                       SEXP,
                                       SEXP,
                                       SEXP);

RcppExport SEXP oem_fit_logistic_sparse(SEXP, 
                                        SEXP, 
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP, 
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP,
                                        SEXP, 
                                        SEXP,
                                        SEXP,
                                        SEXP);

RcppExport SEXP oem_fit_sparse(SEXP, 
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP);

RcppExport SEXP oem_xtx(SEXP, 
                        SEXP, 
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP, 
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP,
                        SEXP);

RcppExport SEXP oem_xval_dense(SEXP, 
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP, 
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP,
                               SEXP);
    
#endif